In [1]:
#반복되는 데이터 넘파이 배열로 처리하는 방법 -> 넘파이가 제공하는 다차원 배열이용
#배열 만들기(넘파이가 제공하는 배열을 ndarray라고 부름)
import numpy as np
a1 = np.array([1,2,3]) #1차원 array -> []로 묶기
print(a1)

[1 2 3]


In [2]:
a2 = np.array([[1,2,3], [4,5,6]]) #2차원 array -> [[]]로 묶기
print(a2)

[[1 2 3]
 [4 5 6]]


In [3]:
a3 = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]]) #3차원 array ->[[[]]]로 묶기
print(a3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [5]:
#배열모양 변경하기
# 1x15 배열을 만들려면 arange()함수 이용 : arrange(시작번호,끝번호,간격), 시작번호와 간격을 생략하면 0부터 끝번호-1까지 반환
c = np.arange(15)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [6]:
#배열 모양을 변경할 때는 배열명.reshape(행,열)
c = c.reshape(3,5) # 1x15 행렬을 3x5행렬로 바꿈
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [8]:
#1차원 -> 3차원으로 바꾸려면
d = np.arange(0,100,5)
d = d.reshape(2,2,5) #(3차원,2차원,1차원) 순으로 기입, 각 차원의 곱은 성분의 개수와 같아야 함
d

array([[[ 0,  5, 10, 15, 20],
        [25, 30, 35, 40, 45]],

       [[50, 55, 60, 65, 70],
        [75, 80, 85, 90, 95]]])

In [9]:
#배열의 스칼라 연산
#nd operation
n1 = np.array([[1,0],
               [0,1]])
n2 = np.array([[1,2],
               [3,4]])
n1+n2

array([[2, 2],
       [3, 5]])

In [10]:
n1-n2

array([[ 0, -2],
       [-3, -3]])

In [11]:
n1*n2 #같은 위치의 원소끼리 곱하는 스칼라 연산임에 주의

array([[1, 0],
       [0, 4]])

In [12]:
n1/n2

array([[1.  , 0.  ],
       [0.  , 0.25]])

In [13]:
n2/n1 #0으로 나누면 경고메세지 + 무한대

C:\Users\1\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ 1., inf],
       [inf,  4.]])

In [14]:
n1+1

array([[2, 1],
       [1, 2]])

In [15]:
n1-1

array([[ 0, -1],
       [-1,  0]])

In [16]:
n1*2

array([[2, 0],
       [0, 2]])

In [17]:
n1/2

array([[0.5, 0. ],
       [0. , 0.5]])

In [18]:
#배열의 벡터연산
np.dot(n1,n2) #n1.dot(n2)와 같은 표현, 벡터 곱

array([[1, 2],
       [3, 4]])

In [19]:
#행끼리, 열끼리 연산
#한줄 연산을 할때는 축을 지정, 열끼리 연산은 axis =0, 행끼리 연산은 axis=1
#배열 내 연산
n3 = np.arange(12).reshape(3,4)
print(n3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [20]:
n3.sum(axis=0) #열합계

array([12, 15, 18, 21])

In [21]:
n3.sum(axis=1) #행합계

array([ 6, 22, 38])

In [22]:
n3.max(axis=1) #각 행에서 최대값

array([ 3,  7, 11])

In [23]:
n3.mean(axis=0) #각 열의 평균값

array([4., 5., 6., 7.])

In [26]:
#축을 지정하지 않으면 한줄 연산을 하지 않고 전체 연사에 대한 연산
print(n3.max()) #최대값
print(n3.min()) #최소값
print(n3.sum()) #전체합
print(n3.mean()) #평균값
print(n3.std()) #표준편차
print(n3.var()) #분산
print(n3.cumsum()) #각 원소의 누적합
print(n3.cumprod()) #각 원소의 누적곱

11
0
66
5.5
3.452052529534663
11.916666666666666
[ 0  1  3  6 10 15 21 28 36 45 55 66]
[0 0 0 0 0 0 0 0 0 0 0 0]


In [27]:
#배열에서 특정 데이터 뽑기 -> 슬라이싱(slicing) 기능 이용
v = np.array([[11,12,13,14,15],
              [21,22,23,24,25],
              [31,32,33,34,35],
              [41,42,43,44,45]])
#array에서 데이터 뽑기
v[1,2] #2행 3열, 데이터가 0부터 시작함에 주의

23

In [28]:
v[1][2] #v[1,2]와 같은 표현

23

In [30]:
v[:,1] #전체 행, 2열 데이터 추출

array([12, 22, 32, 42])

In [31]:
v[1:3, 1] #2~3행, 2열 데이터 추출

array([22, 32])

In [32]:
v[1, :] #2행 전체 데이터 추출, v[1] 과도 같음

array([21, 22, 23, 24, 25])

In [33]:
v[1]

array([21, 22, 23, 24, 25])

In [34]:
#팬더스 이용 -> 팬더스를 이용하면 자료 구조를 엑셀의 스프레드시트와 같은 형태로 만들어 대용량 데이터 처리 가능
#팬더스로 1차원 데이터를 처리할 때는 시리즈(Series)로, 2차원 데이터를 처리할 때는 데이터프레임(DataFrame) 사용

#시리즈
import pandas as pd
prices = [1000,1010, 1020] #주가
#주가에 해당하는 날짜를 지정하기 위해 data_range('시작날짜', '끝날짜', periods = 날짜수, freq = '주기') 이용, 끝날짜와 periods 둘중 하나를 지정, freq는 생략 가능
#date_range()에서 freq는 'D', 'W', 'M' 등으로 지정, 기본값은 'D'
dates = pd.date_range('20181201', periods=3)
dates

DatetimeIndex(['2018-12-01', '2018-12-02', '2018-12-03'], dtype='datetime64[ns]', freq='D')

In [35]:
pd.date_range('20180101', '20180131', freq='W') # 주기를 'W'로 지정하면 일주일 단위로 지정

DatetimeIndex(['2018-01-07', '2018-01-14', '2018-01-21', '2018-01-28'], dtype='datetime64[ns]', freq='W-SUN')

In [36]:
s = pd.Series(prices, index=dates) #주가를 데이터로, 날짜를 인덱스로 하는 시리즈 생성
s

2018-12-01    1000
2018-12-02    1010
2018-12-03    1020
Freq: D, dtype: int64

In [37]:
s2 = pd.Series(prices) # 인덱스를 지정하지 않으면 0부터 일렬로 번호 생성
s2

0    1000
1    1010
2    1020
dtype: int64

In [39]:
s2[3] = 1030 #시리즈에 데이터를 추가할 때는 시리즈명[인덱스] = 값
s2

0    1000
1    1010
2    1020
3    1030
dtype: int64

In [40]:
#날짜로 인덱스가 매겨진 시리즈 s에 데이터를 추가하려면 pd.to_datetime()함수 이용
#pd.to_datetime('날짜')는 문자열을 날짜형식으로 전환, '날짜'는 20100205, 2010-02-05 등 날짜 형식이면 됨
s[pd.to_datetime('2018-12-04')] = 1030 #인덱스를 이용한 데이터추가
s

2018-12-01    1000
2018-12-02    1010
2018-12-03    1020
2018-12-04    1030
Freq: D, dtype: int64

In [41]:
s[2] #시리즈도 리스트나 배열처럼 특정 데이터를 골라서 뽑을 수 있음

1020

In [42]:
s['2018-12-03'] #인덱스를 이용한 데이터추출

1020

In [43]:
# 데이터프레임 생성
prices = {'A전자' : [1000,1010,1020],
          'B화학' : [2000,2010,2020],
          'C금융' : [3000,3010,3020]}
df1 = pd.DataFrame(prices) #딕셔너리를 데이터프레임으로 변환
df1

A전자   B화학   C금융
0  1000  2000  3000
1  1010  2010  3010
2  1020  2020  3020

In [44]:
df2 = pd.DataFrame(prices, index=dates) #인덱스가 있는 데이터프레임
df2

A전자   B화학   C금융
2018-12-01  1000  2000  3000
2018-12-02  1010  2010  3010
2018-12-03  1020  2020  3020

In [45]:
#데이터프레임 조회
#데이터프레임.iloc[줄번호, 열번호] 로 데이터 조회, 열번호는 생략가능(생략하면 열 전체)
df2.iloc[0] #1행

A전자    1000
B화학    2000
C금융    3000
Name: 2018-12-01 00:00:00, dtype: int64

In [47]:
df2.iloc[:, 0] #1열

2018-12-01    1000
2018-12-02    1010
2018-12-03    1020
Freq: D, Name: A전자, dtype: int64

In [48]:
df2.iloc[0,0] #1행, 1열

1000

In [49]:
#레이블을 이용해서 데이터 조회가능
#데이터프레임.loc['행레이블', '열레이블'], '열레이블'은 생략가능(생략하면 전체선택)
df2.loc['2018-12-01']

A전자    1000
B화학    2000
C금융    3000
Name: 2018-12-01 00:00:00, dtype: int64

In [50]:
df2.loc[:, 'A전자']

2018-12-01    1000
2018-12-02    1010
2018-12-03    1020
Freq: D, Name: A전자, dtype: int64

In [54]:
df2.loc['2018-12-01', 'A전자']

1000

In [55]:
df2['A전자'] #df2.A전자와 동일, 리스트로 반환

2018-12-01    1000
2018-12-02    1010
2018-12-03    1020
Freq: D, Name: A전자, dtype: int64

In [56]:
df2['A전자']['2018-12-01'] #df2.loc[:, 'A전자']['2018-12-01']와 동일한 표현

1000

In [57]:
#데이터 프레임에 데이터 추가
#데이터프레임['종목명'] = [시세]처럼 지정후 추가 가능
df2['D엔터'] = [4000,4010,4020]
df2

A전자   B화학   C금융   D엔터
2018-12-01  1000  2000  3000  4000
2018-12-02  1010  2010  3010  4010
2018-12-03  1020  2020  3020  4020

In [59]:
#데이터프레임에 종목을 추가할 때 이미 만들어준 시리즈 이용가능, 데이터프레임['레이블'] = 시리즈 처럼 지정
df2['E텔레콤'] = s
df2

A전자   B화학   C금융   D엔터  E텔레콤
2018-12-01  1000  2000  3000  4000  1000
2018-12-02  1010  2010  3010  4010  1010
2018-12-03  1020  2020  3020  4020  1020

In [61]:
#데이터프레임 확장
#인덱스에 없는 값도 추가하려면 concat 기능 이용 : pd.concat(A,B, axis=1), aixs = 0은 행방향, axis=1은 열방향, A와 B라는 데이터프레임 병합
s.name = 'F소프트'
s

2018-12-01    1000
2018-12-02    1010
2018-12-03    1020
2018-12-04    1030
Freq: D, Name: F소프트, dtype: int64

In [62]:
df2 = pd.concat([df2, s], axis=1)
df2

A전자     B화학     C금융     D엔터    E텔레콤  F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020
2018-12-04     NaN     NaN     NaN     NaN     NaN  1030

In [63]:
#12월 7일에 12월 1일보다 시세가 60원씩 오른 것을 추가하려면
#1. df2에서 12월 1일자 데이터를 추출해서 df3에 저장
df3 = df2.iloc[0]
#2. 60원씩 더해주기
df3 = df3 + 60
#3. df3에 12월 7일이라고 레이블 지정
df3.name = pd.to_datetime('20181207')
#4. df2에 행 추가
df2 = df2.append(df3) #행 추가할 때는 데이터프레임.append(추가할 데이터프레임)
df2

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-04     NaN     NaN     NaN     NaN     NaN  1030.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0

In [65]:
#12월 6일에는 12월 1일보다 50원씩 올랐다고 한다면
df3 = df2.iloc[0] + 50
df3.name = pd.to_datetime('20181206')
df2= df2.append(df3)
df2

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-04     NaN     NaN     NaN     NaN     NaN  1030.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0
2018-12-06  1050.0  2050.0  3050.0  4050.0  1050.0  1050.0

In [66]:
#날짜를 순서대로 하려면 sort_index() 이용, 데이터프레임.sort_index(axis=0, ascending=True) , axis = 0은 행방향, True면 오름차순
df2.sort_index(inplace = True)
df2

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-04     NaN     NaN     NaN     NaN     NaN  1030.0
2018-12-06  1050.0  2050.0  3050.0  4050.0  1050.0  1050.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0

In [67]:
#데이터프레임에서 데이터 빼기
#데이터프레임.drop(label, axis=0) , axis=1이면 열삭제
df2.drop(pd.to_datetime('2018-12-06')) #행삭제, 인덱스 지정시 to_datetime()형식을 이용해야 함
# 저장 하려면 df2 = df2.drop~으로 해야함

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-04     NaN     NaN     NaN     NaN     NaN  1030.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0

In [68]:
df2.drop([pd.to_datetime('2018-12-02'), pd.to_datetime('2018-12-06')]) #여러 행삭제

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-04     NaN     NaN     NaN     NaN     NaN  1030.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0

In [69]:
df2.drop('D엔터', axis=1) #열삭제

A전자     B화학     C금융    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  1010.0  1010.0
2018-12-03  1020.0  2020.0  3020.0  1020.0  1020.0
2018-12-04     NaN     NaN     NaN     NaN  1030.0
2018-12-06  1050.0  2050.0  3050.0  1050.0  1050.0
2018-12-07  1060.0  2060.0  3060.0  1060.0  1060.0

In [70]:
df2.drop(['C금융', 'E텔레콤'], axis=1) #여러 열삭제, 레이블을 []로 묶어줘야 함

A전자     B화학     D엔터    F소프트
2018-12-01  1000.0  2000.0  4000.0  1000.0
2018-12-02  1010.0  2010.0  4010.0  1010.0
2018-12-03  1020.0  2020.0  4020.0  1020.0
2018-12-04     NaN     NaN     NaN  1030.0
2018-12-06  1050.0  2050.0  4050.0  1050.0
2018-12-07  1060.0  2060.0  4060.0  1060.0

In [71]:
#데이터프레임 구멍 메우기(보간법)
#NaN 를 없애려면 데이터프레임.dropna(), 다른값으로 메우려면 데이터프레임.fillna() 명령 이용
df2.dropna()

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-06  1050.0  2050.0  3050.0  4050.0  1050.0  1050.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0

In [73]:
#데이터를 대체하려면 데이터프레임.fillna(대체값 또는 방법), 0또는 1 등 값을 지정하면 해당값으로, method = ffill/bfill이면 앞뒤값으로 변경
df2.fillna(0) #0으로바꿈

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-04     0.0     0.0     0.0     0.0     0.0  1030.0
2018-12-06  1050.0  2050.0  3050.0  4050.0  1050.0  1050.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0

In [74]:
df2.fillna(method='ffill') #앞의 값으로 채움

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-04  1020.0  2020.0  3020.0  4020.0  1020.0  1030.0
2018-12-06  1050.0  2050.0  3050.0  4050.0  1050.0  1050.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0

In [76]:
df2.fillna(method='bfill') #뒤의 값으로 채움

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-04  1050.0  2050.0  3050.0  4050.0  1050.0  1030.0
2018-12-06  1050.0  2050.0  3050.0  4050.0  1050.0  1050.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0