In [1]:
# Tensor 생성하기 : 리스트, np.array, tf.constant
import numpy as np
import tensorflow as tf

In [2]:
m1 = [[1.0, 2.0], [3.0,4.0]] #텐서플로우는 부동 소수점 처리 (dtype = float32 이용해도 됨)
m2 = np.array([[1.0, 2.0],[3.0,4.0]])
m3 = tf.constant([[1., 2.],[3.,4.]]) # m3 = tf.costant([[1,2],[3,4]], dtype = tf.float32)

print(type(m1))
print(type(m2))
print(type(m3))

<class 'list'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [9]:
#리스트, np.array -> tensor로 변경하기
t1 = tf.convert_to_tensor(m1, dtype = tf.float32)
t2 = tf.convert_to_tensor(m2, dtype = tf.float32)
t3 = tf.convert_to_tensor(m3, dtype = tf.float32)

print(type(t1))
print(type(t2))
print(type(t3))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [10]:
# 텐서플로우는 그래프를 define하는 영역과 run하는 영역이 나누어짐(기본이 graph define)
# run 하려면 Session을 정의해 줘야 함
sess = tf.Session()
print('OPEN SESSION')

def print_tf(x):
    print('type is %s' % type(x))
    print('value is %s' % x)

OPEN SESSION


In [11]:
hello = tf.constant('hello, tensorflow')
print_tf(hello) # 해당 노드의 상태만 보여줌

type is <class 'tensorflow.python.framework.ops.Tensor'>
value is Tensor("Const_7:0", shape=(), dtype=string)


In [13]:
#그래프(노드)를 실행하려면 
hello_run = sess.run(hello)
print_tf(hello_run)

type is <class 'bytes'>
value is b'hello, tensorflow'


In [15]:
a = tf.constant([1.0])
a_run = sess.run(a)
print_tf(a_run) #run을 했을 때 출력은 numpy로 바뀜

type is <class 'numpy.ndarray'>
value is [1.]


In [16]:
b = tf.constant([2.0])
a_plus_b = tf.add(a,b)
print_tf(a_plus_b)

type is <class 'tensorflow.python.framework.ops.Tensor'>
value is Tensor("Add:0", shape=(1,), dtype=float32)


In [17]:
a_plus_b_run = sess.run(a_plus_b)
print_tf(a_plus_b_run)

type is <class 'numpy.ndarray'>
value is [3.]


In [19]:
# Variable -> 그래프 내에서 최적화되는 변수
w = tf.Variable(tf.random_normal([5,2], stddev = 0.1))
print_tf(w)

type is <class 'tensorflow.python.ops.variables.Variable'>
value is <tf.Variable 'Variable:0' shape=(5, 2) dtype=float32_ref>


In [20]:
w_run = sess.run(w) # -> 오류 발생, 텐서플로우는 변수를 run 하기 위해서는 반드시 변수 초기화를 해줘야 함

FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[Node: _retval_Variable_0_0 = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable)]]

In [21]:
sess.run(w.initializer)
w_run = sess.run(w)
print_tf(w_run)

type is <class 'numpy.ndarray'>
value is [[-0.0829398   0.11545559]
 [-0.09265785  0.07729744]
 [-0.16403513 -0.25058106]
 [-0.12560253 -0.23286203]
 [ 0.05008984 -0.02140562]]


In [23]:
# tf.Variable이 여러개인 경우 tf.global_variables_initializer() 이용
w2 = tf.Variable(tf.random_normal([5,2], stddev = 0.1))
sess.run(tf.global_variables_initializer())
w2_run = sess.run(w2)
print_tf(w2_run)

type is <class 'numpy.ndarray'>
value is [[-0.04746721 -0.00067108]
 [ 0.18119034  0.02137794]
 [ 0.20098744  0.2099504 ]
 [ 0.08162178  0.07555748]
 [-0.0512546   0.1412143 ]]


In [24]:
# Placeholder : 데이터를 담는 container라고 생각, 그래프를 만들 때 이용하는 틀로써 이를 미리 지정해두면 나중에 그래프를 실행할 때 데이터만 넣어주면 됨
x = tf.placeholder(tf.float32, [None, 5]) # x는 n x 5 matrix
print_tf(x)

type is <class 'tensorflow.python.framework.ops.Tensor'>
value is Tensor("Placeholder:0", shape=(?, 5), dtype=float32)


In [25]:
oper = tf.matmul(x, w)
print(oper)

Tensor("MatMul:0", shape=(?, 2), dtype=float32)


In [27]:
# x에 데이터 할당해서 계산해보기
data = np.random.rand(1,5)
oper_run = sess.run(oper, feed_dict = {x:data})
print_tf(oper_run)

type is <class 'numpy.ndarray'>
value is [[0.19658217 0.22410524]]


In [28]:
# eval()
a = tf.constant([5.])
b = tf.constant([6.])
c = a*b
print(c.eval()) # -> 오류 발생, Session이 없기 때문에 eval()은 실행 X

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`

In [29]:
with tf.Session():
    print(c.eval())

[30.]


In [30]:
# InteractiveSession()을 설정하면 default 세션으로 설정되므로 바로 eval() 사용 가능
sess = tf.InteractiveSession()
print(c.eval())

[30.]


In [33]:
t = tf.constant([1,2,3,4])
print(t.shape)
print(tf.shape(t).eval())

(4,)
[4]


In [36]:
# matmul vs multiply : matmul은 행렬간의 곱을, multiply는 각 원소간의 곱을 출력
sess1 = tf.InteractiveSession()
mat1 = tf.constant([[3.,3.]])
mat2 = tf.constant([[2.],[2.]])

print(tf.shape(mat1).eval())
print(tf.shape(mat2).eval())

[1 2]
[2 1]


In [37]:
tf.matmul(mat1, mat2).eval()

array([[12.]], dtype=float32)

In [38]:
tf.multiply(mat1,mat2).eval() # 자동으로 Broadcasting이 돼서 2x2행렬로 나옴

array([[6., 6.],
       [6., 6.]], dtype=float32)

In [39]:
(mat1*mat2).eval()

array([[6., 6.],
       [6., 6.]], dtype=float32)